[env:esp32-s3-n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; --- Đồng bộ tốc độ cổng kiểm tra dữ liệu ---
monitor_speed = 115200
; --- Cấu hình tài nguyên bộ nhớ vật lý N16R8 ---
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv 
build_flags = 
    -DBOARD_HAS_PSRAM
board_build.arduino.memory_type = qio_opi 

; --- Thư viện điều khiển camera chính thức ---
lib_deps =
  esp32-camera
  knolleary/PubSubClient@^2.8.0  ;